export enum SectionEnum {
    PRESENTATION = 'PRESENTATION',
    CONCOURS = 'CONCOURS',
    PROJETS = 'PROJETS',
    FORMATIONS = 'FORMATIONS',
    EXPERIENCES = 'EXPERIENCES',
    COMPETENCES = 'COMPETENCES',
    HOME = 'HOME',
    THRALL = 'THRALL',
    TYRANDE = 'TYRANDE',
    RED = 'RED',
    STEAMPUNK = 'STEAMPUNK',
    PB = 'PB',
    TARECGOSA = 'TARECGOSA',
    SOGEKING = 'SOGEKING',
    TALANJI = 'TALANJI'
}