export enum SectionEnum {
    PRESENTATION = 'PRESENTATION',
    CONCOURS = 'CONCOURS',
    CONVENTIONS = 'CONVENTIONS',
    PROJETS = 'PROJETS',
    FORMATIONS = 'FORMATIONS',
    EXPERIENCES = 'EXPERIENCES',
    COMPETENCES = 'COMPETENCES',
    HOME = 'HOME',
    THRALL = 'THRALL',
    TYRANDE = 'TYRANDE',
    RED = 'RED',
    STEAMPUNK = 'STEAMPUNK',
    PB = 'PB'
}